"""
model_utils.py

Utility functions for model creation, loading, and multi-model ensemble operations.
This module provides a clean interface for:
- Creating model instances with consistent configurations
- Loading single or multiple model checkpoints
- Finding available checkpoints in a directory

This separation improves code readability and reusability across different scripts.

Note on Multi-Model Ensemble:
    When using multiple models for quality-filtered ensemble, all auxiliary models
    share the same architecture but may have different weights. The conditioning
    information (cond) is generated by the main model's transformer and passed
    to all models' diffusion components, which is valid since they share the same
    architecture and conditioning dimension.
"""

import os
import glob
import torch
from typing import List, Optional, Tuple

from DSTPP import GaussianDiffusion_ST, Transformer_ST, Model_all, ST_Diffusion
from DSTPP import RectifiedFlow, RF_Diffusion
from DSTPP.RF_Model_all import RF_Model_all

# ============ Model Configuration Constants ============
# Centralized configuration to avoid hardcoding in multiple places
MODEL_CONFIG = {
    'd_model': 64,
    'd_rnn': 256,
    'd_inner': 128,
    'n_layers': 4,
    'n_head': 4,
    'd_k': 16,
    'd_v': 16,
    'dropout': 0.1,
    'cond_dim': 64,
    'CosSin': True,
}


def create_model(opt, device: torch.device):
    """
    Create a new model instance based on the configuration.
    
    Args:
        opt: Configuration options containing model_type, timesteps, dim, etc.
        device: Device to create the model on
    
    Returns:
        Model: A new RF_Model_all or Model_all instance
    """
    # Spatio-temporal Encoder (using centralized config)
    transformer = Transformer_ST(d_model=MODEL_CONFIG['d_model'],
                                 d_rnn=MODEL_CONFIG['d_rnn'],
                                 d_inner=MODEL_CONFIG['d_inner'],
                                 n_layers=MODEL_CONFIG['n_layers'],
                                 n_head=MODEL_CONFIG['n_head'],
                                 d_k=MODEL_CONFIG['d_k'],
                                 d_v=MODEL_CONFIG['d_v'],
                                 dropout=MODEL_CONFIG['dropout'],
                                 device=device,
                                 loc_dim=opt.dim,
                                 CosSin=MODEL_CONFIG['CosSin']).to(device)

    if opt.model_type == 'ddpm':
        model = ST_Diffusion(n_steps=opt.timesteps, dim=1 + opt.dim, condition=True, cond_dim=MODEL_CONFIG['cond_dim']).to(device)
        diffusion = GaussianDiffusion_ST(model,
                                         loss_type=opt.loss_type,
                                         seq_length=1 + opt.dim,
                                         timesteps=opt.timesteps,
                                         sampling_timesteps=opt.samplingsteps,
                                         objective=opt.objective,
                                         beta_schedule=opt.beta_schedule).to(device)
        Model = Model_all(transformer, diffusion).to(device)
    elif opt.model_type == 'rf':
        model = RF_Diffusion(n_steps=opt.timesteps, dim=1 + opt.dim, condition=True, cond_dim=MODEL_CONFIG['cond_dim']).to(device)
        rf = RectifiedFlow(model, loss_type=opt.loss_type, seq_length=1 + opt.dim, timesteps=opt.timesteps,
                           sampling_timesteps=opt.samplingsteps).to(device)
        Model = RF_Model_all(transformer, rf).to(device)
    else:
        raise ValueError(f"Unsupported model type: {opt.model_type}")

    return Model


def load_model(opt, device: torch.device, checkpoint_path: str):
    """
    Load a model from a checkpoint file.
    
    Args:
        opt: Configuration options
        device: Device to load the model on
        checkpoint_path: Path to the .pkl checkpoint file
    
    Returns:
        Model: Loaded model with weights
    """
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint_path}")

    Model = create_model(opt, device)
    Model.load_state_dict(torch.load(checkpoint_path, map_location=device))
    Model.eval()
    print(f"Model loaded from: {checkpoint_path}")
    return Model


def load_multiple_models(opt, device: torch.device, checkpoint_paths: List[str]) -> List:
    """
    Load multiple models from checkpoint files for ensemble evaluation.
    
    Args:
        opt: Configuration options
        device: Device to load models on
        checkpoint_paths: List of paths to checkpoint files
    
    Returns:
        List of loaded models
    """
    models = []
    for path in checkpoint_paths:
        try:
            model = load_model(opt, device, path)
            models.append(model)
        except Exception as e:
            print(f"Warning: Failed to load model from {path}: {e}")

    print(f"Successfully loaded {len(models)} models for ensemble evaluation.")
    return models


def find_model_checkpoints(model_dir: str, epochs: Optional[List[int]] = None) -> List[str]:
    """
    Find model checkpoint files in a directory.
    
    Args:
        model_dir: Directory containing model checkpoints
        epochs: Optional list of specific epochs to load. If None, load all available.
    
    Returns:
        List of checkpoint file paths (sorted by epoch number)
    """
    if not os.path.exists(model_dir):
        raise FileNotFoundError(f"Model directory not found: {model_dir}")

    if epochs is not None:
        # Load specific epochs
        paths = []
        for epoch in epochs:
            path = os.path.join(model_dir, f'model_{epoch}.pkl')
            if os.path.exists(path):
                paths.append(path)
            else:
                print(f"Warning: Checkpoint not found: {path}")
        return paths
    else:
        # Load all available checkpoints
        pattern = os.path.join(model_dir, 'model_*.pkl')
        paths = glob.glob(pattern)
        # Sort by epoch number
        paths.sort(key=lambda x: int(os.path.basename(x).replace('model_', '').replace('.pkl', '')))
        return paths


def parse_epochs_string(epochs_str: str) -> List[int]:
    """
    Parse a comma-separated string of epochs into a list of integers.
    
    Args:
        epochs_str: String like "100,120,140,160,180"
    
    Returns:
        List of epoch numbers
    """
    if not epochs_str:
        return None
    return [int(e.strip()) for e in epochs_str.split(',')]
